### ISSUE TITLE
using a local directory as source for images

### ISSUE THREAD

**Issue by muzzol** [DimitriMikadze/vanilla-slideshow#2]
this is a feature request about using a local dir as source for images.

instead of defining every image, it would be nice if you specify a dir with images and the script just load them.

**Comment by DimiMikadze** [comment]
But what if you don't want all images from that dir or images you want to show are located in separate folders ?

**Comment by muzzol** [comment]
it's trivial to make links or just copy the ones you want in a new folder.
I think is lot easier than editing an HTML file everytime you want to add a new file.
but feel free to discard this request if you don't find it apropiate :)

**Comment by DimiMikadze** [comment]
Thank you for your feedback! 

you can make changes to repo and push them if you think its better for repo itself, thanks!
